
package com.parametra.ws.com.parametra.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmpleadoImplService", targetNamespace = "http://impl.parametra.com/", wsdlLocation = "http://localhost:1515/ws/empleado?wsdl")
public class EmpleadoImplService
    extends Service
{

    private final static URL EMPLEADOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLEADOIMPLSERVICE_EXCEPTION;
    private final static QName EMPLEADOIMPLSERVICE_QNAME = new QName("http://impl.parametra.com/", "EmpleadoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1515/ws/empleado?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLEADOIMPLSERVICE_WSDL_LOCATION = url;
        EMPLEADOIMPLSERVICE_EXCEPTION = e;
    }

    public EmpleadoImplService() {
        super(__getWsdlLocation(), EMPLEADOIMPLSERVICE_QNAME);
    }

    public EmpleadoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLEADOIMPLSERVICE_QNAME, features);
    }

    public EmpleadoImplService(URL wsdlLocation) {
        super(wsdlLocation, EMPLEADOIMPLSERVICE_QNAME);
    }

    public EmpleadoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLEADOIMPLSERVICE_QNAME, features);
    }

    public EmpleadoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpleadoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEmpleadoService
     */
    @WebEndpoint(name = "EmpleadoImplPort")
    public IEmpleadoService getEmpleadoImplPort() {
        return super.getPort(new QName("http://impl.parametra.com/", "EmpleadoImplPort"), IEmpleadoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEmpleadoService
     */
    @WebEndpoint(name = "EmpleadoImplPort")
    public IEmpleadoService getEmpleadoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.parametra.com/", "EmpleadoImplPort"), IEmpleadoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLEADOIMPLSERVICE_EXCEPTION!= null) {
            throw EMPLEADOIMPLSERVICE_EXCEPTION;
        }
        return EMPLEADOIMPLSERVICE_WSDL_LOCATION;
    }

}
