
package com.parametra.ws.com.parametra.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://service.parametra.com/")
public class Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.parametra.ws.com.parametra.service.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception(String message, com.parametra.ws.com.parametra.service.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Exception(String message, com.parametra.ws.com.parametra.service.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.parametra.service.Exception
     */
    public com.parametra.ws.com.parametra.service.Exception getFaultInfo() {
        return faultInfo;
    }

}
