
package com.parametra.ws.com.parametra.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.parametra.ws.com.parametra.service.EmpleadoEntity;
import com.parametra.ws.com.parametra.service.ObjectFactory;
import com.parametra.ws.com.parametra.service.Tiempos;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEmpleadoService", targetNamespace = "http://service.parametra.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEmpleadoService {


    /**
     * 
     * @param apellidos
     * @param tipoDocumento
     * @param fechaNacimineto
     * @param salario
     * @param cargo
     * @param fechaVinculacionEmp
     * @param nombres
     * @return
     *     returns com.parametra.service.Tiempos
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.parametra.com/", className = "com.parametra.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.parametra.com/", className = "com.parametra.service.AddResponse")
    @Action(input = "http://service.parametra.com/IEmpleadoService/addRequest", output = "http://service.parametra.com/IEmpleadoService/addResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://service.parametra.com/IEmpleadoService/add/Fault/Exception")
    })
    public Tiempos add(
        @WebParam(name = "nombres", targetNamespace = "")
        String nombres,
        @WebParam(name = "apellidos", targetNamespace = "")
        String apellidos,
        @WebParam(name = "tipo_documento", targetNamespace = "")
        String tipoDocumento,
        @WebParam(name = "fecha_nacimineto", targetNamespace = "")
        String fechaNacimineto,
        @WebParam(name = "fecha_vinculacion_emp", targetNamespace = "")
        String fechaVinculacionEmp,
        @WebParam(name = "cargo", targetNamespace = "")
        String cargo,
        @WebParam(name = "salario", targetNamespace = "")
        double salario)
        throws Exception
    ;

    /**
     * 
     * @param arg1
     * @param id
     * @return
     *     returns com.parametra.service.EmpleadoEntity
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://service.parametra.com/", className = "com.parametra.service.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.parametra.com/", className = "com.parametra.service.UpdateResponse")
    @Action(input = "http://service.parametra.com/IEmpleadoService/updateRequest", output = "http://service.parametra.com/IEmpleadoService/updateResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://service.parametra.com/IEmpleadoService/update/Fault/Exception")
    })
    public EmpleadoEntity update(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "arg1", targetNamespace = "")
        EmpleadoEntity arg1)
        throws Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.parametra.com/", className = "com.parametra.service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.parametra.com/", className = "com.parametra.service.DeleteResponse")
    @Action(input = "http://service.parametra.com/IEmpleadoService/deleteRequest", output = "http://service.parametra.com/IEmpleadoService/deleteResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://service.parametra.com/IEmpleadoService/delete/Fault/Exception")
    })
    public Boolean delete(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.parametra.service.EmpleadoEntity>
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.parametra.com/", className = "com.parametra.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.parametra.com/", className = "com.parametra.service.FindAllResponse")
    @Action(input = "http://service.parametra.com/IEmpleadoService/findAllRequest", output = "http://service.parametra.com/IEmpleadoService/findAllResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://service.parametra.com/IEmpleadoService/findAll/Fault/Exception")
    })
    public List<EmpleadoEntity> findAll()
        throws Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns com.parametra.service.EmpleadoEntity
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://service.parametra.com/", className = "com.parametra.service.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://service.parametra.com/", className = "com.parametra.service.FindByIdResponse")
    @Action(input = "http://service.parametra.com/IEmpleadoService/findByIdRequest", output = "http://service.parametra.com/IEmpleadoService/findByIdResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://service.parametra.com/IEmpleadoService/findById/Fault/Exception")
    })
    public EmpleadoEntity findById(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws Exception
    ;

}
